################################### Default Configuration ############################
baseurl = "https://www.aidbots.in"
title = "Aidbots"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = ["fr"] # desable language from here

publishDir = "docs"

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Droid+Serif:400|Josefin+Sans:300,400,600,700"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
# [[params.plugins.css]]
# link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"
[[params.plugins.css]]
link = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"


###################################### Navigation ######################################

# homepage section menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

# # main menu
# [[menu.main]]
# name = "Products"
# URL = "products"
# weight = 2

# main menu
[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

# # footer menu
# [[menu.footer]]
# name = "Blog"
# URL = "blog"
# weight = 1

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 2

# [[menu.footer]]
# name = "Terms & Conditions"
# URL = "terms-conditions"
# weight = 3

[[menu.footer]]
name = "Privacy Policy"
URL = "privacy-policy"
weight = 4



# Navigation buttons
[params.navigation_button]
enable = true
label = "Get a Quote"
link = "contact"  




########################### Default parameters ##########################
[params]
logo = "images/Aidbots_logo.png"
logo_width = "100px"
# Meta data
description = "This is meta description"
author = "Anshul Paigwar"
# currency
currency = "$"
# contact form action
contact_form_action = "https://getform.io/f/7153f350-59e6-4a33-b39c-cb49e0d8e02c" # contact form works with https://formspree.io
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://aidbots.us2.list-manage.com/subscribe/post?u=8f1a3d773f3410ea7a5cf4473&amp;id=895895f5b1" # not working from here had to directly place url in subscription.html
mailchimp_form_name = "b_8f1a3d773f3410ea7a5cf4473_895895f5b1" # replace this code with yours



############################# social site ########################
[[params.social]]
title = "facebook"
icon = "tf-ion-social-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/ivlabs/"

[[params.social]]
title = "instagram"
icon = " tf-ion-social-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/ivlabs/"

[[params.social]]
title = "linkedin"
icon = " tf-ion-social-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/ivlabs-vnit/"

[[params.social]]
title = "Youtube"
icon = "tf-ion-social-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UC2Ud1ZH23JJvmnb6aHCu51g/videos"














################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Designed remotely in the City of Oranges and the foothills of the French Alps."


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
